# Generated by Django 5.1.5 on 2025-05-08 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_delete_vehicle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="driver",
            name="license",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="license"
            ),
            preserve_default=False,
        ),
    ]
