# Generated by Django 5.1.5 on 2025-05-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ratings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rating",
            name="rating",
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
