# Generated by Django 5.1.5 on 2025-04-06 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("started", "Started"),
                    ("initiated", "Initiated"),
                    ("completed", "Completed"),
                    ("canceled", "Canceled"),
                    ("user_canceled", "User Canceled"),
                    ("expired", "Expired"),
                    ("refunded", "Refunded"),
                    ("partially_refunded", "Partially Refunded"),
                    ("pending", "Pending"),
                ],
                default="started",
                max_length=20,
            ),
        ),
    ]
