# Generated by Django 5.1.5 on 2025-04-20 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0007_alter_booking_payment_status"),
        ("payments", "0002_alter_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="booking",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="bookings.booking",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="pidx",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
