# Generated by Django 5.1.5 on 2025-04-20 14:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0003_payment_booking_payment_pidx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="response_data",
        ),
        migrations.RemoveField(
            model_name="payment",
            name="token",
        ),
    ]
