# Generated by Django 5.1.5 on 2025-03-24 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("users", "0002_delete_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vehicle_color", models.CharField(max_length=30)),
                ("vehicle_company", models.CharField(max_length=50)),
                (
                    "vehicle_type",
                    models.CharField(
                        choices=[
                            ("Suv", "SUV"),
                            ("Sedan", "Sedan"),
                            ("Hatchback", "Hatchback"),
                            ("4X4", "4X4"),
                            ("PickUp", "Pickup"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "vehicle_fuel_type",
                    models.CharField(
                        choices=[
                            ("Diesel", "Diesel"),
                            ("Petrol", "Petrol"),
                            ("Electric", "Electric"),
                        ],
                        max_length=20,
                    ),
                ),
                ("vehicle_number", models.CharField(max_length=20)),
                ("sitting_capacity", models.IntegerField()),
                (
                    "driver",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicle",
                        to="users.driver",
                    ),
                ),
            ],
        ),
    ]
