# # Generated by Django 5.1.5 on 2025-03-19 17:03

# from django.db import migrations


# class Migration(migrations.Migration):
#     dependencies = [
#         ("bookings", "0001_initial"),
#     ]

#     operations = []

from django.db import migrations

def populate_locations(apps, schema_editor):
    Location = apps.get_model('bookings', 'Location')
    
    # Create locations based on the original FARE_MAPPING
    locations_data = [
        {'name': 'Mustang', 'fare': 25000},
        {'name': 'Jhinu', 'fare': 7000},
        {'name': 'Poon hill', 'fare': 10000},
        {'name': 'Sidhing', 'fare': 7000},
    ]
    
    for location_data in locations_data:
        Location.objects.create(**location_data)

class Migration(migrations.Migration):
    # Look at your migrations folder for the most recent migration name
    dependencies = [
        ('bookings', '0001_initial'),  # Replace if your initial migration has a different name
    ]

    operations = [
        migrations.RunPython(populate_locations),
    ]