# Generated by Django 5.1.5 on 2025-03-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0002_populate_location_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="location_image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
