# Generated by Django 5.1.5 on 2025-04-03 04:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0003_location_location_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
