# Generated by Django 5.1.5 on 2025-04-12 16:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0005_booking_bookingitime"),
    ]

    operations = [
        migrations.RenameField(
            model_name="booking",
            old_name="bookingItime",
            new_name="booking_time",
        ),
    ]
