# Generated by Django 5.1.5 on 2025-04-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookings", "0006_rename_bookingitime_booking_booking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("partial", "Partially Paid"),
                    ("confirmed", "Confirmed"),
                    ("canceled", "Canceled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
