# Generated by Django 5.1.1 on 2024-12-04 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driverName', models.CharField(max_length=50)),
                ('driverEmail', models.EmailField(max_length=254)),
                ('driverPhoneNumber', models.IntegerField()),
                ('lisenceImage', models.ImageField(upload_to='lisence')),
                ('driverPassword', models.CharField(max_length=150)),
                ('driverStatus', models.CharField(choices=[('busy', 'busy'), ('free', 'free')], max_length=5)),
                ('driverVerification', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerName', models.CharField(max_length=20)),
                ('passengerPhone', models.IntegerField()),
                ('passengerEmail', models.EmailField(max_length=254, unique=True)),
                ('passengerPassword', models.CharField(max_length=150)),
                ('passengerPhoto', models.ImageField(blank=True, upload_to='passengers')),
                ('passengerOtp', models.CharField(blank=True, max_length=5, null=True)),
                ('passengerVerified', models.BooleanField(default=False)),
                ('Created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleColor', models.CharField(max_length=30)),
                ('vehicleCompany', models.CharField(max_length=50)),
                ('vehicleType', models.CharField(choices=[('Suv', 'Suv'), ('Sedan', 'Sedan'), ('Hatchback', 'Hatchback'), ('4X4', '4X4'), ('PickUp', 'Pickup')], max_length=20)),
                ('vehicleFuelType', models.CharField(choices=[('Diesel', 'Diesel'), ('Petrol', 'Petrol'), ('Electric', 'Electric')], max_length=20)),
                ('vehicleNumber', models.CharField(max_length=20)),
                ('relation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='goTrip.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='VehicleImages')),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='goTrip.vehicle')),
            ],
        ),
    ]
