# Generated by Django 5.1.1 on 2024-10-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passengerName', models.CharField(max_length=20)),
                ('passengerPhone', models.IntegerField()),
                ('passengerEmail', models.EmailField(max_length=254)),
                ('passengerpassword', models.CharField(max_length=20)),
                ('passengerPhoto', models.ImageField(blank=True, upload_to='passengers')),
            ],
        ),
    ]
