# Generated by Django 5.1.1 on 2024-12-12 08:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goTrip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('booking_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('accepted', 'Accepted'), ('driver_selected', 'Driver Selected'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='requested', max_length=20)),
                ('accepted_drivers', models.ManyToManyField(blank=True, related_name='accepted_bookings', to='goTrip.driver')),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goTrip.driver')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goTrip.passenger')),
            ],
        ),
    ]
