# Generated by Django 5.1.1 on 2024-10-13 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goTrip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='passengerOtp',
            field=models.CharField(default=0, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passenger',
            name='passengerVerified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passengerEmail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
