# Generated by Django 5.1.1 on 2024-10-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goTrip', '0002_passenger_passengerotp_passenger_passengerverified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='passengerOtp',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='passengerpassword',
            field=models.CharField(max_length=150),
        ),
    ]
