# Generated by Django 5.1.1 on 2024-10-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goTrip', '0004_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='driverVerification',
            field=models.BooleanField(default=False),
        ),
    ]
