# Generated by Django 5.1.1 on 2024-11-20 02:23

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goTrip', '0009_alter_driver_driverpassword_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='Created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2024, 11, 20, 8, 6, 34, 597867)),
            preserve_default=False,
        ),
    ]
